FROM python:2.7.13
WORKDIR /opt/inter-domain-resource-module
COPY . ./
RUN pip install --no-cache-dir --upgrade -r requirements.txt
#EXPOSE 8008 8888
#####ENTRYPOINT ["python", "escape.py"]
#####CMD ["--debug", "--rosapi", "--config", "config/escape-static-dummy.config"]
